{% set name = "atomium" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/samirelanduk/atomium/archive/v{{ version }}.tar.gz
  sha256: c3e1254b6e3f741a450acc31d3ae402f72a55b9acfc55a45df6216bfebfc5c1e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - requests
    - msgpack-python
    - paramiko
    - tqdm
    - rmsd
    - valerius

test:
  imports:
    - atomium

about:
  home: https://github.com/samirelanduk/atomium
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python molecular modeller (with .pdb/.cif/.mmtf parsing and production)

  description: |
    atomium is a molecular modeller and file parser, capable of reading
    from and writing to .pdb, .cif and .mmtf files.
  doc_url: https://atomium.samireland.com/
  dev_url: https://github.com/samirelanduk/atomium

extra:
  recipe-maintainers:
    - jaimergp
    - samirelanduk
